FROM openjdk:8-jdk-alpine
ADD target/HeartBeatMicroservice-1.0-SNAPSHOT-jar-with-dependencies.jar com.sd.laborator.HeartBeatMicroservice.jar

ENTRYPOINT ["java","-jar", "com.sd.laborator.HeartBeatMicroservice.jar"]