FROM openjdk:8-jdk-alpine
ADD target/TeacherMicroservice-1.0-SNAPSHOT-jar-with-dependencies.jar com.sd.laborator.TeacherMicroservice.jar

ENTRYPOINT ["java","-jar", "com.sd.laborator.TeacherMicroservice.jar"]