FROM openjdk:8-jdk-alpine
ADD target/MessageManagerMicroservice-1.0-SNAPSHOT-jar-with-dependencies.jar com.sd.laborator.MessageManagerMicroservice.jar

ENTRYPOINT ["java","-jar", "com.sd.laborator.MessageManagerMicroservice.jar"]